# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [6]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.22.3
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [9]:
y = np.array([100, 20, 34])
print(y.nbytes)

24


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
python -c"import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-10-9b89d0187dec>, line 1)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [13]:

x=x[::-1]
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
a=np.array([1,2,0,0,4,0])
print(np.where(a != 0))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
np.random.random((3,3,3))

array([[[0.06215473, 0.56673654, 0.75498113],
        [0.49246332, 0.89241822, 0.87119077],
        [0.07975376, 0.55482313, 0.78995829]],

       [[0.17346573, 0.61208781, 0.28050105],
        [0.399448  , 0.88803808, 0.70912974],
        [0.98864742, 0.95138328, 0.89841221]],

       [[0.84391638, 0.95342613, 0.75754837],
        [0.60359339, 0.16653871, 0.6611509 ],
        [0.06718827, 0.57843042, 0.42459897]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [18]:
arr=np.random.random((10,10))

arr

array([[0.74980002, 0.40599149, 0.10794018, 0.91216298, 0.24498644,
        0.88902377, 0.80490329, 0.58270982, 0.52056712, 0.91408283],
       [0.1417211 , 0.77416193, 0.56126643, 0.89425012, 0.30531729,
        0.43993707, 0.97814441, 0.74045778, 0.98227038, 0.15977065],
       [0.19411271, 0.96017445, 0.63125107, 0.26379038, 0.85099653,
        0.59900216, 0.34069477, 0.84278127, 0.54999196, 0.21328134],
       [0.82926496, 0.88476646, 0.74454492, 0.88279676, 0.48037645,
        0.92494111, 0.40634553, 0.61269547, 0.46711697, 0.94154835],
       [0.76895426, 0.16289704, 0.37026279, 0.95651507, 0.85650321,
        0.82453679, 0.85800735, 0.3903134 , 0.13384965, 0.23423685],
       [0.31037793, 0.43080859, 0.15675463, 0.5493579 , 0.26985417,
        0.69214725, 0.19154736, 0.51881929, 0.62109529, 0.14770808],
       [0.02109741, 0.31483539, 0.95979078, 0.99357902, 0.77127261,
        0.25247079, 0.69937012, 0.89844129, 0.9398816 , 0.65874752],
       [0.94446841, 0.10198726, 0.4628940

In [19]:
mi=arr.min()
mi


0.021097413307934798

In [20]:
ma=arr.max()
ma

0.9945825243265317

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
v=arr=np.random.random((10))
v


array([0.36122907, 0.76374946, 0.48504709, 0.5947124 , 0.88913358,
       0.90001921, 0.00792231, 0.15200479, 0.08478211, 0.00266401])

In [22]:
ms=v.mean()
ms

0.42412640264986046

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [23]:
c=np.ones((3,3))

c[1:-1, 1:-1]=0
c

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [24]:
c = np.pad(c, pad_width=1, mode='constant', constant_values=0)
print(c)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [26]:
false

NameError: name 'false' is not defined

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [27]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [28]:
s=np.zeros((8,8))
print(s)
s[1::2,::2]=1
s[::2,1::2]=1
s

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [145]:
h = np.arange(1,337).reshape(6,7,8)
print(h)
print(np.unravel_index(100,(6,7,8)))


[[[  1   2   3   4   5   6   7   8]
  [  9  10  11  12  13  14  15  16]
  [ 17  18  19  20  21  22  23  24]
  [ 25  26  27  28  29  30  31  32]
  [ 33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55  56]]

 [[ 57  58  59  60  61  62  63  64]
  [ 65  66  67  68  69  70  71  72]
  [ 73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88]
  [ 89  90  91  92  93  94  95  96]
  [ 97  98  99 100 101 102 103 104]
  [105 106 107 108 109 110 111 112]]

 [[113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128]
  [129 130 131 132 133 134 135 136]
  [137 138 139 140 141 142 143 144]
  [145 146 147 148 149 150 151 152]
  [153 154 155 156 157 158 159 160]
  [161 162 163 164 165 166 167 168]]

 [[169 170 171 172 173 174 175 176]
  [177 178 179 180 181 182 183 184]
  [185 186 187 188 189 190 191 192]
  [193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208]
  [209 210 211 212 213 214 215 216]
  [217 218 219 220 221

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [36]:
t=np.tile(np.array([[0,1],[1,0]]),(4,4))
t

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [46]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()

x = (x - xmin)/(xmax - xmin)

print("After normalization:")
print(x)


Original Array:
[[0.28552082 0.24947547 0.355288   0.99101629 0.49190961]
 [0.29912482 0.33299393 0.81589598 0.2950084  0.73137481]
 [0.23651171 0.5232173  0.94525098 0.72416812 0.55150757]
 [0.39232377 0.86927337 0.31278921 0.38872972 0.23866883]
 [0.49329957 0.87625032 0.19973549 0.25328427 0.07498677]]
After normalization:
[[0.22983326 0.19048371 0.30599584 1.         0.45514127]
 [0.24468431 0.28165813 0.80882678 0.24019054 0.71655774]
 [0.17633159 0.48931887 0.95003948 0.70869043 0.52020245]
 [0.34642661 0.86709716 0.25960128 0.3425031  0.17868644]
 [0.45665865 0.87471368 0.13618417 0.19464166 0.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [56]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)


1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [71]:
A=np.random.random((5,3))
A

array([[0.25036226, 0.66204437, 0.24004   ],
       [0.53482065, 0.75967393, 0.62000842],
       [0.97178255, 0.90681335, 0.21128771],
       [0.28052189, 0.56792881, 0.58849884],
       [0.48703316, 0.25316812, 0.04902138]])

In [72]:
A=np.random.random((5,3))
A


array([[0.11634936, 0.459399  , 0.55732158],
       [0.2930601 , 0.36730443, 0.84744086],
       [0.98365374, 0.67989357, 0.32304581],
       [0.39317463, 0.13408826, 0.47936634],
       [0.62125209, 0.53856092, 0.73067916]])

In [73]:
result = np.dot(A, B)
result

array([[0.67299818, 0.44509824],
       [0.72651715, 0.6159076 ],
       [0.92617841, 1.018833  ],
       [0.37636469, 0.46491936],
       [0.89481662, 0.85986454]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [80]:
c = np.arange(10)
c[3:9]=np.dot(c[3:9],-1)
c

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
#the output is 10
#from numpy import *
#print(sum(range(5),-1)) here -1 is the axis

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [94]:
# list1 = [5, 6, 9]
# Z = np.array(list1)
# print(Z)
# legal:
# Z**Z
# 2 << Z >> 2
# Z <- Z
# 1j*Z
# Z/1/1
# not legal
# Z<Z>Z


[5 6 9]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [158]:
# print(np.array([1,2,4]) / np.array([2,2,2]))
# print(np.array([1,2,4]) // np.array([2,2,2]))


print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

[0.5 1.  2. ]
[0 1 2]
nan
0
[-9.22337204e+18]


<ipython-input-158-26f1bdaf9450>:5: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-158-26f1bdaf9450>:6: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [102]:
def round_array(x,y):
    return np.round(x,y)
test = np.array([32.11, 51.5, 0.112])
print(round_array(test,0))

[32. 52.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [116]:
array1=np.array([1,2,3,4,5])
array2=np.array([1,4,7,8,6])
print(np.intersect1d(array1, array2))


[1 4]
