# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [41]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [42]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.22.3
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

#### 3. Create a null vector of size 10 (★☆☆)

In [43]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [44]:
y = np.array([100, 20, 34])
print(y.nbytes)

24


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
python -c"import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [45]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [46]:
x = np.arange(10, 50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [47]:

x=x[::-1]
x

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [48]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [49]:
a=np.array([1,2,0,0,4,0])
print(np.where(a != 0))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [50]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [51]:
np.random.random((3,3,3))

array([[[0.25557579, 0.60665165, 0.27652056],
        [0.84886997, 0.51957657, 0.66417748],
        [0.12850523, 0.29693879, 0.49485482]],

       [[0.72901493, 0.88212881, 0.27582054],
        [0.88728659, 0.82551252, 0.48720048],
        [0.33163721, 0.12190218, 0.25537217]],

       [[0.39027016, 0.68884248, 0.55440313],
        [0.51808518, 0.71121949, 0.36289009],
        [0.9000884 , 0.27334827, 0.35730526]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [55]:
arr=np.random.random((10,10))

arr

array([[0.11045312, 0.70509371, 0.02017796, 0.89635627, 0.90367989,
        0.13317722, 0.68434616, 0.06278917, 0.66838101, 0.25484372],
       [0.11412229, 0.25815694, 0.11112722, 0.74510895, 0.5112132 ,
        0.48982718, 0.11566164, 0.21573464, 0.73740572, 0.51273479],
       [0.17545621, 0.85506029, 0.07265109, 0.3288843 , 0.07148726,
        0.98385356, 0.68111974, 0.54178221, 0.75339673, 0.63291767],
       [0.74005479, 0.60148506, 0.97546274, 0.6671507 , 0.88680773,
        0.14657419, 0.33598424, 0.63293233, 0.96775344, 0.52418095],
       [0.10887447, 0.14852446, 0.76235491, 0.61007274, 0.63458065,
        0.19471644, 0.78385812, 0.6254592 , 0.71487394, 0.60581673],
       [0.36217046, 0.00684742, 0.85241511, 0.01453145, 0.89410451,
        0.47555691, 0.26775287, 0.7101919 , 0.47200579, 0.74379571],
       [0.51353151, 0.92121621, 0.20172651, 0.13499439, 0.78423509,
        0.41106894, 0.34083066, 0.05160258, 0.11451587, 0.08491045],
       [0.413084  , 0.05102133, 0.2026417

In [62]:
mi=arr.min()
mi


0.006847416444768162

In [63]:
ma=arr.max()
ma

0.9838535599192676

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [68]:
v=arr=np.random.random((10))
v


array([0.84222835, 0.13712387, 0.24740272, 0.41899669, 0.30662279,
       0.07035996, 0.59209254, 0.55329463, 0.88122155, 0.84342227])

In [70]:
ms=v.mean()
ms

0.4892765380102313

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [86]:
c=np.ones((3,3))

c[1:-1, 1:-1]=0
c

array([[1., 1., 1.],
       [1., 0., 1.],
       [1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [87]:
c = np.pad(c, pad_width=1, mode='constant', constant_values=0)
print(c)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 0. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [115]:
Z = np.diag(1+np.arange(4), k = -1)
print (Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [119]:
s=np.zeros((8,8))
print(s)
s[1::2,::2]=1
s[::2,1::2]=1
s

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)